#hmwk4

## data input

### install packages
```{r}
install.packages("countrycode")
```

### load packages
```{r}
library(sf)
library(tidyverse)
library(dbplyr)
library(here)
library(janitor)
library(countrycode)
```

### read in the csv
```{r}
inequal_stats <- read_csv(here::here("4_2_hmwk4_data", 
                   "HDR21-22_Composite_indices_complete_time_series.csv")
                    locale = locale(encoding = "latin1"),
                    na = " ", skip=0)
```

### view the .csv
```{r}
inequal_stats
```

### read in the shape file
```{r}
shape_hmwk4 <- st_read(here::here("4_2_hmwk4_data",                          "World_Countries_Generalized", "World_Countries_Generalized.shp"))
```

### clean names and select columns and harmonise country code column for joining
```{r}
inequal_cols<- inequal_stats %>%
    clean_names()%>%
    select(iso3, country, gii_2019, gii_2010)%>%
    mutate(difference=gii_2019-gii_2010)%>%
  
    mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))%>%
  mutate(iso_code2=countrycode(iso3, origin = 'iso3c', destination = 'iso2c'))
```

## joining data 

### left join inequal_cols to the hmwk4 shape file
```{r}
inequal_cols_join <- shape_hmwk4 %>%
    clean_names() %>%
    left_join(.,inequal_cols,
              # change to "aff_iso" = "iso_code"
              by = c ("iso" = "iso_code"))
```


